apiVersion: v1
kind: Secret
metadata:
  name: controller-manager
  namespace: {{ .Values.spec.OPENSHIFT_NAMESPACE }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  
# stringData:
#   github_token: "{{ .Values.spec.GHE_TOKEN }}"

data:
  github_token: Z2hwXzVqVTQ2YTRvUmF5RlZHUlkyeDVQZkxkNHlZaHAwazFMTWxQOQ==
