apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-runner-app
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
     argocd.argoproj.io/sync-wave: "10"
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.spec.OPENSHIFT_NAMESPACE }}

  project: default
  source:
    path: runner-deploy
    repoURL: https://github.com/squoc/arc-testing
    targetRevision: HEAD

  syncPolicy:
    syncOptions:
    - Replace=true
    - ServerSideApply=true
    automated:
      selfHeal: true
      prune: true

